### PR TITLE
Enable nbd,xfs and twofish in C2 defconfig

### PR DESCRIPTION
**Pull request by Ray-future**
Patch enables network block devices, twofish crypto, xfs filesystem and lirc in C2 defconfig.
I've tested and everything works good.

### CODE REVIEW

**Comment by Obihoernchen** [comment]
I would set the following, too!
CONFIG_XFS_QUOTA
CONFIG_XFS_POSIX_ACL

**Comment by Ray-future** [comment]
You're right! Thanks

**Comment by mdrjr** [comment]
What's the point of enabling LIRC without the correct LIRC driver?

Apart from this question I'm good to merge this.

**Comment by Ray-future** [comment]
You're probably right. I'll remove it. Thought that maybe someone might want to build an own driver. Saw  someone who wrote a lirc gpio driver for the RPI.

**Comment by mdrjr** [comment]
Thank you :) another huge thank you.

**Pull request merged**
