### PR TITLE
Make ondemand governor easily available again

### PR DESCRIPTION
**Pull request by Obihoernchen**
`CONFIG_CPU_FREQ_GOV_ONDEMAND=y`

### CODE REVIEW

**Comment by Fourdee** [comment]
+1 for this:
http://dietpi.com/phpbb/viewtopic.php?f=9&t=1927&p=7388#p7386

Ondemand will reduce power consumption and heat, when not under full load and max clocks.

**Comment by Obihoernchen** [comment]
Yep and with proper configuration the performance is the same as well. Even for IO load.

**Comment by filemoon** [comment]
+1 for this:

I would like to ask for Conservative governor too.

+CONFIG_CPU_FREQ_GOV_ONDEMAND=y
 +CONFIG_CPU_FREQ_GOV_CONSERVATIVE=y

**Comment by Obihoernchen** [comment]
@mdrjr :)

**Comment by Obihoernchen** [comment]
@mdrjr what do you think?

**Comment by mdrjr** [comment]
Merged :)

**Pull request merged**
