### PR TITLE
Upgrade to 4.9.45 by patching the diff onto the hardkernel 4.9.y branch.

### PR DESCRIPTION
**Pull request by uDude**
I merged the following patch from kernel.org to 4.9.y  (see kernel.ord, they moved stable to 4.9.45 from 4.9.44).  There was very little that should affect arm processors.  It unfortunately does not resolve the firefox 55 crash on start up problem on the 4.9 kernel for arm.  The applied patch in the attached file was generated by  https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/rawdiff/?id=v4.9.45&id2=v4.9.44&dt=0

[linux_kernel_v4.9.44-v4.9.45.patch.gz](https://github.com/hardkernel/linux/files/1254831/linux_kernel_v4.9.44-v4.9.45.patch.gz)

The patch was applied the standard way:

patch --strip 1 < Patch_file

### CODE REVIEW

**Comment by uDude** [comment]
If you have a dev branch that you'd rather see us submit pull requests for let me know.  I checked tobetter's repo but didn't see 4.9.44 or 4.9.y.

**Comment by mdrjr** [comment]
Hello @uDude,

While I appreciate your effort, we don't track upstream by patching with the diffs.
I just merge the upstream tag into our tree. 

That way we can have all the history and commits from upstream :)

**Comment by uDude** [comment]
That makes perfect sense.  I was annoyed by losing  comments, too.  Just
consider me as an early tester.  I've purchased quite a few odroids and
don't mind the time to test kernels and distros.

Have a great day.

**Comment by Dmole** [comment]
@uDude you should close this PR.

**Pull request closed without merging**
