### PR TITLE
odroidxu3-3.10.y: Update to 3.10.94

### PR DESCRIPTION
**Pull request by moonman**
A full merge of mainline up to 3.10.94. Tested on XU4 under load for 3 days. No regressions.

### CODE REVIEW

**Comment by Obihoernchen** [comment]
I can confirm.
Tested for 5 days, no issues at all.

**Comment by umiddelb** [comment]
please consider to [enable the Kernel options needed to run Docker](https://github.com/umiddelb/armhf/wiki/Installing,-running,-using-docker-on-armhf-%28ARMv7%29-devices#see-whats-missing), see [this issue](https://github.com/hardkernel/linux/issues/147) as well:

```
ubuntu@xu4:~/kernel/3.10/linux$ bash ../../check-config.sh .config | grep -v enabled
info: reading kernel config from .config ...

Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_DEVPTS_MULTIPLE_INSTANCES: missing
- CONFIG_CGROUP_DEVICE: missing
- CONFIG_CPUSETS: missing
- CONFIG_MEMCG: missing

Optional Features:
- CONFIG_MEMCG_KMEM: missing
- CONFIG_MEMCG_SWAP: missing
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_BLK_CGROUP: missing
- CONFIG_BLK_DEV_THROTTLING: missing
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_EXT3_FS: missing
- CONFIG_EXT3_FS_XATTR: missing
- CONFIG_EXT3_FS_POSIX_ACL: missing
- CONFIG_EXT3_FS_SECURITY: missing
    (enable these ext3 configs if you are using ext3 as backing filesystem)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
      (note that some kernels include AUFS patches but not the AUFS_FS flag)
  - "btrfs":
  - "devicemapper":
  - "overlay":
    - CONFIG_OVERLAY_FS: missing
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing
```

**Comment by moonman** [comment]
How is this related to this pull request? Make the changes necessary to
defconfig and submit a new pull request.

**Comment by umiddelb** [comment]
OK, https://github.com/moonman/linux/pull/1

**Pull request closed without merging**
