### PR TITLE
Add amvideocap odroid-c1 dtb

### PR DESCRIPTION
**Pull request by 0xfischer**
Need this device to grab data for DIY Ambilight Project with hyperion on odroid-c1.

### CODE REVIEW

**Comment by mdrjr** [comment]
Why you need it? How you are using it? 
Also why paste that comments ? I dont want those comments.

**Comment by 0xfischer** [comment]
I have a DIY Ambilight project with hyperion (https://github.com/tvdzwan/hyperion) on odroid-c1 as MediaCenter.  Hyperion is not able to grab (capture) video data from playing videos in Kodi, because the videos are playing hw-accelerated with Amcodec/Amplayer. I almost want to add my code to hyperion, but I'm not finished yet. But I can use the device with boblight-aml. With this code http://pastebin.com/PxqzHVcW it works very smooth on the odroid-c1.

**Comment by mdrjr** [comment]
Hello StrikerHF,

DTB only change is enough? The defconfig option is enabled for this ? 
If so.. I'll merge it.

**Comment by ricardona** [comment]
@StrikerHF I changed dts and compiled the boblight-aml client but the system hangs completly after 15-30 minutes (blue led is without heartbeat). do you have similar behaviour?

[Details](http://forum.odroid.com/viewtopic.php?f=116&t=12680)

**Pull request merged**
