### PR TITLE
ODROID-C2: integrated support for aufs and Docker

### PR DESCRIPTION
**Pull request by aa64**
Hi @mdrjr 

these patches will allow to run Docker on the ODROID-c2. Is there any chance to test the [overlayfs backport](http://forum.odroid.com/viewtopic.php?f=138&t=18757#p124940) as well? This may replace aufs.

Cheers
Uli

### CODE REVIEW

**Comment by mdrjr** [comment]
Hello @aa64 .

I will tend to prefer OverlayFS over aufs..

What do you think? I can merge OverlayFS support on our 3.14..

**Comment by umiddelb** [comment]
Hello @mdrjr 

would be great to have OverlayFS support in the 3.14 kernel. I'm getting kernel oops when using aufs with Docker under Debian (interestingly not under Arch, although it's the same kernel and the same Docker binary).

**Comment by mdrjr** [comment]
Here we go! 

Commit 11e207c5635b55f1a1cf2f846e0b0251f09cc220 adds Overlay fs support.

**Comment by umiddelb** [comment]
At this time Docker refuses to start, and even with some tweaking in `fs/overlayfs/super.c` Docker is unable to run a container. So aufs support might be necessary as well.

**Comment by umiddelb** [comment]
I'm afraid we cannot skip aufs support in 3.14, [Docker doesn't run with overlayfs v21](https://twitter.com/frazelledazzell/status/699355494675165184)

**Comment by mdrjr** [comment]
So, v22 is what it needs?

**Comment by umiddelb** [comment]
hm, actually the version introduced in 3.18 (I'm not sure, if its v22).

Anyway, I'm about to prepare a PR which should merge aufs support without conflict resolution.

What about mainline support for S905? Do you know if there is anyone working on it?

**Comment by aa64** [comment]
to be continued [here](https://github.com/hardkernel/linux/pull/161)

**Pull request closed without merging**
