### PR TITLE
Made fan starts smoother when reaches 50 degrees in auto mode

### PR DESCRIPTION
**Pull request by ghost**
In the old code when CPU reaches 50 degrees fan->duty changes from 1 to (255 \* 50 / 80 = 159), that's cooling fast CPU by 1 degree again to 50 and cooler stops, and so on... This noise is annoying and may be this algorithm would be better?

When temperature is above 50 - everything is doing like it did before. After 50 degrees duty would be in interval [1, 255] instead of [159, 255]. But there would be a problem, that CPU will be cooling much less in temperature about 50-60. Well, it can be fixed by setting FAN_TEMP_START to 40 or 35 degrees.

### CODE REVIEW

**Comment by mdrjr** [comment]
And why make those hardcoded? 
Making those as sysfs nodes would be much better for ones that wants to change that behavior.

**Comment by ghost** [comment]
okay) I'll try to do so. thanks

**Comment by ghost** [comment]
mdrjr, You want me to make a sysfs node only for fan starting temperature? Cause if the throttle temp is 83, it is better to keep the max temperature hardcoded...

**Comment by ghost** [comment]
But I didn't tested it yet... Have no access to my odroid from my job place. Well, what do you think about it?)

**Comment by ghost** [comment]
Here I made all my job in one commit and tested it. That works fine.

**Comment by marlemion** [comment]
Would it be possible to merge this into the mali_r4 branch as well?

**Comment by mdrjr** [comment]
That branch is useless. I've removed it.. r4p0 support is now merge on main branch for 3.8

**Pull request merged**
