### PR TITLE
Added support for the DVB devices: DVBSky USB, TechoTrend CT2 4400 and TechnoTrend CT2 4650

### PR DESCRIPTION
**Pull request by joukestoel**
I back-ported the needed code for the DVBSky USB, TechnoTrend CT2 4400 and TechnoTrend CT2 4650 CI DVB USB devices and checked the correct working using a TT 4650.

Because I used the latest version (end of march 2015) of the v4l project (media tree) and worked my way back from the `drivers/media/usb/dvb-usb-v2/dvbsky.c` file (I looked for all the files that where used by this driver, transitively) I probably also accidentally copied in other stuff (like definitions of other devices) as well...

To enable the driver a `make menuconfig` should be run to enable the following items:
Device Drivers --> Multimedia Support --> Media Controller API --> Enable Media Controller for DVB
Device Drivers --> Multimedia Support --> Media USB Adapters --> DVBSky USB support

### CODE REVIEW

**Comment by xforze** [comment]
Hi !
I have a DVBSky S960CI USB Box. Unfortunatelly, its not working for me with added dvb support to kernel. (lsusb: Bus 001 Device 004: ID 0572:960c Conexant Systems (Rockwell), Inc.)

The modules are compiled and loaded correctly from the current kernel version (here is the output of lsmod):
m88ts2022               4910  1
m88ds3103              11846  1
dvb_usb_dvbsky          8783  0
dvb_usb_v2             14672  1 dvb_usb_dvbsky

But no dvb application (mumudvb, szap) is able to controll the card, I always get an error, here an example:

szap -r -n 3651
reading channels from file '/root/.szap/channels.conf'
zapping to 3651 'M1':
sat 0, frequency = 10759 MHz H, symbolrate 30000000, vpid = 0x0031, apid = 0x0032 sid = 0x0002
using '/dev/dvb/adapter0/frontend0' and '/dev/dvb/adapter0/demux0'
Version: 5.10    FE_CAN { DVB-S + DVB-S2 }
FE_SET_TONE failed: Resource temporarily unavailable
FE_SET_VOLTAGE failed: Resource temporarily unavailable
FE_DISEQC_SEND_MASTER_CMD failed: Resource temporarily unavailable
FE_DISEQC_SEND_BURST failed: Resource temporarily unavailable
FE_SET_TONE failed: Resource temporarily unavailable

With the previous kernel version (without the added dvb supprt), my card was working fine, I just had to apply the kernel patches from http://www.dvbsky.net/Support_linux.html (linux-3.12-dvbsky-patch) and rebuild the modules.

Which card are you using ?

**Comment by muradm** [comment]
Hi @joukestoel 

Is it possible to port this patch to odroidc-3.10.y-android?

Thanks in advance

**Comment by joukestoel** [comment]
Hi @xforze, sorry for the very late reply.
I am using a TechnoTrend CT2 4650-CI so I am not able to check for the DVBSky.
What is dmesg telling?

**Comment by joukestoel** [comment]
Hi @muradm,

I think it would be possible to create a similar patch for the android branch but it would again take some considerable time.

I did it by cross-compiling the kernel and using the dvb source from the latests media_tree.  See http://forum.odroid.com/viewtopic.php?f=117&t=10847 for more information. 

I have no doubt that it can be done, it will just take a lot of elbow grease...

**Pull request merged**
