### PR TITLE
compile warnings

### PR DESCRIPTION
**Pull request by Dmole**
Banish them.

### CODE REVIEW

**Comment by mdrjr** [comment]
Did you tested USB3 stuff with this patch? Its the only thing that scares me to merge it.

**Comment by Dmole** [comment]
Yes; I tested with:
- unplugged power for a minute
- booted with 1 USB3 hub and 3 USB3 drives connected
- mounted and used with no issues or anything of note in dmesg 

Theoretically there are no functional changes to USB3, just [re]moved some dead code.
hdmi and wifi have functional changes to avoid uninitialized variable access.

**Comment by Dmole** [comment]
4.9.16 should also use this
https://patchwork.kernel.org/patch/8352011/

**Comment by Dmole** [comment]
@mdrjr I rebased and removed the usb changes. Please review.

**Review by mdrjr — APPROVED** [review]

**Pull request merged**
