### PR TITLE
This patch replaces 'entry.S' and 'assembler.h' with the kernel 3.16 …

### PR DESCRIPTION
**Pull request by mlinuxguy**
This patch fixes the problem with GDB being unable to set breakpoints in programs
It is based off of the 3.16 entry.S fixes

### CODE REVIEW

**Comment by mlinuxguy** [comment]
These are optimized stack saves from arm.com for entry.S  They were added 29 Sep 2014 after our 3.14 kernel

**Comment by moonlinux** [comment]
I have tested you github branch and I got compilation error.
Earlier I tried the first uploaded patch and it failed to boot after building the kernel.
Few of the patches are good and should be considered by HK.

**Comment by mlinuxguy** [comment]
If you use their original uInitrd it boost fine.
When I create one with my kernel it hangs here:
set_hpll_od3_clk_div[216] div = 6
j = 5  vid_clk_div = 1
hdmitx phy setting done
hdmitx: set enc for VIC: 4
enc_vpu_bridge_reset[977]
Error: Bad gzipped data
ID=e139ce78-9841-40fe-8823-96a304a09859 rootwait rw ${condev}
no_console_suspend hdmimode=${m} m_bpp=${m_bpp} vout=${vout} fsck.fix=yes
net.ifnames=0"
cfgload: setenv loadaddr "0x11000000"
cfgload: setenv dtb_loadaddr "0x1000000"
cfgload: setenv initrd_## Loading init Ramdisk from Legacy Image at
13000000 ...
   Image Name:   uInitrd
   Image Type:   ARM Linux RAMDisk Image (uncompressed)
   Data Size:    30917557 Bytes = 29.5 MiB
   Load Address: 00000000
   Entry Point:  00000000
   Verifying Checksum ... tx VIC = 4
config HPLL = 2970
HPLL: 0xc800023d
config HPLL done
set_hpll_od3_clk_div[216] div = 6
j = 5  vid_clk_div = 1
hdmitx phy setting done
hdmitx: set enc for VIC: 4
enc_vpu_bridge_reset[977]
Error: Bad gzipped data

**Comment by mlinuxguy** [comment]
You need a new uInitrd for my kernel to boot
The command to use is:
root@odroid64:~# cat makeinitrd.sh
#!/bin/bash
cd /root/linux
update-initramfs -c -t -k `uname -r`
mkimage -A arm64 -O linux -T ramdisk -C none -a 0 -e 0 -n uInitrd -d /boot/initrd.img-3.14.29+ /boot/uInitrd-`uname -r`
Then copy /boot/uInitrd over like this:
root@odroid64:/boot# cp uInitrd-3.14.29+ /media/boot/uInitrd

**Pull request closed without merging**
