### PR TITLE
Fix for 2 issues in the AOCEC driver

### PR DESCRIPTION
**Pull request by Ray-future**
The following commits fix an issue where cec_node_init was called through the hpd plugin and started to poll for the AML cec keyboard mode when in libcec mode.

There was also an issue where TX got busy if the user was pressing buttons during libcec initialization (SONY TV). This is mitigated by setting inactive source before switching to libcec mode. Also a minor change in  handling TX_BUSY. I'm not sure if it fixes the problem. User also reported it could be temperature related.

### CODE REVIEW

**Comment by bkrepo** [comment]
Thank you for your contribution!
@Raybuntu, could you follow [the Linux kernel coding style](https://www.kernel.org/doc/Documentation/CodingStyle)? Other things look like good for me.
- Example> ~/.vimrc

```
set noexpandtab
set tabstop=8
set shiftwidth=8
set softtabstop=8
```

**Comment by mdrjr** [comment]
Hello @Raybuntu  Did you tested those changes against patched libcec3? 

@bkrepo Can you test this changes with our new v2.0 image?

**Comment by Ray-future** [comment]
**@bkrepo**: The file came originally directly from Amlogic. I didn't want to mix up different indentation but if you want I can try to reindent the whole file to "8 spaces"? But the commit is gonna get big then? Or is there something else I'm doing wrong in my coding? 

**@mdrjr**: Yes I've tested it and also did some LibreElec users on the odroid forum. I can only test it on samsung so I'm not entirely sure it'll work everywhere. I'm also not sure the TX_BUSY issue can be solved entirely. For one user there is weird stuff going on in the chip and it's still a blackbox to me since I don't have the whole doc. But it might be a hardware issue too since I'm only seeing it for one user. It's working for him most of the time but after a while (and he suspects a temperature issue) it stops working (with or without that fix):
http://forum.odroid.com/viewtopic.php?f=138&t=20415&p=144053#p144013

`cectx c810023c.aocec: cec_ll_rx(): CEC: rx msg len: 13   dat: 01 01 01 01 01 01 01 01 01 01 01 01 01`

I've never seen such a RX for cec. Looks like cec ping messages getting queued and appended somehow inside the chip? It happens right after a TX has a timeout and the TX state becomes TX_BUSY. I haven't found an answer for that.

**Comment by bkrepo** [comment]
After applying this PR(I tested on LG Simplink TV), 
- cec-client is working well
- But, CEC does not work in Kodi(Look like need updating libcec for Kodi)

PS. @Raybuntu, if you feel burden about the cleanup source code, I will do it later. Just enjoy C2. :-)

**Comment by Ray-future** [comment]
@bkrepo: And did it work before the PR in kodi? Can you provide a kodi debug log so I can see what's going on. Is kodi linked against the patched libcec version? I can only imagine that the commit https://github.com/hardkernel/linux/pull/203/commits/840c9beb04ab534e42ae01f7b0e8146cb33e9060 is causing the issue. I've noticed that on Sony TV's the node is initialized multiple times. Maybe we can drop that commit. Does the AML cec keyboard mode work on startup? I can revert that commit. Can you try removing that ifndef.

**Comment by bkrepo** [comment]
Kodi debug log here:
- https://gist.github.com/bkrepo/667672cea2ec70c2e30983fc04bb9590

After reverting https://github.com/hardkernel/linux/pull/203/commits/54d0b71419e218ebdc9131a9d33233ddedcb5b2d commit, CEC is working well in Kodi.

**Comment by Ray-future** [comment]
Do you have the option set in kodi to "activate source" on startup?
System -> Settings -> System -> Input Devices -> Peripherals -> CEC adapter

 I don't see CEC messages in your kodi log, are you sure it's a complete debug log?
Settings → System → Debugging and turn on Enable debug logging

The commit you reverted sends an inactive source for the aml cec keyboard mode which is the default. But libcec/kodi should AS on startup. Maybe the DEVICE_MENU_INACTIVE is making trouble on LG TV's. But you're saying that cec-client works after you input "as"?
I thought that commit could mitigate the issue the user had when pushing buttons during kodi startup but I can revert that if it's really not a kodi issue.

**Comment by bkrepo** [comment]
You mean "_Switch source to this device on startup_" option? Yes, it is enabled. 
I tested Kodi with disable the "_Send "Inactive source" command on shutdown_" option. And then, CEC is work now. 

This LG TV is able to turn on/off Simplink function. Is it be the reason of this problem?

Kodi log here: (Disable the "_Send "Inactive source" command on shutdown_" option)
- https://gist.github.com/bkrepo/5622286d74423de9c734e256b8a1ebd0

**Comment by Ray-future** [comment]
Would you be so kind an also provide a kern.log with aocec debug enabled and kodi starting up. Something is not right. I rather revert that commit if it's causing so much trouble.

I can revert https://github.com/hardkernel/linux/pull/203/commits/54d0b71419e218ebdc9131a9d33233ddedcb5b2d
and https://github.com/hardkernel/linux/pull/203/commits/840c9beb04ab534e42ae01f7b0e8146cb33e9060

If it solves your problem.

**Comment by bkrepo** [comment]
dmesg with _'cec_msg_dbg_en = 1'_ while Kodi runnig
- https://gist.github.com/bkrepo/66aaa7208bed719f6bc21098bb8b12bb

In this case, CEC is working even if 'TX ERROR' message is printed. (???) Maybe this is related to CEC initialization timing.

**Comment by Ray-future** [comment]
The TX_ERROR is intended (according to the cec spec). Kodi tries to ping other devices and can't find them. Log is fine but you already said it was working. I'd like to see a log when it's failing.

But I'll propably go ahead and revert the two commits. Most important is the fix here https://github.com/hardkernel/linux/pull/203/commits/85e494caf28b31a7f521dec0a24288fe04e7edc0
This was a bug and it's important to get fixed, the other commits were to fix a TX_BUSY bug for a user but that didn't help after all obviously. Sorry if I wasted your time. And thanks for testing it!

**Pull request merged**
