### PR TITLE
Integrate aufs filesystem

### PR DESCRIPTION
**Pull request by paralin**
This patch applies aufs 4 to the kernel sources for odroid xu4.

http://aufs.sourceforge.net/

Signed-off-by: Christian Stewart christian@paral.in

### CODE REVIEW

**Comment by paralin** [comment]
This fixes #115

**Comment by paralin** [comment]
This will require a few updates for 4.2.

**Comment by paralin** [comment]
In commit 680baacbca69d18a6d7315374ad83d05ac9c0977 `nd_set_link` as used by aufs is removed and replaced with `nd_jump_link`.

**Comment by paralin** [comment]
See http://sourceforge.net/p/aufs/mailman/message/34289816/

```
Hello all,

Today is Monday. I usually release aufs on every Monday and it is
expected to be release aufs4.x-rcN for linux-4.2-rc[12] today.
But fortunately/unfortunately I am very busy now and have to suspend my
aufs development for a while, at least for this month. In other words, I
will not release aufs4.x-rcN for almost all linux-4.2-rcN series.
If everything goes well, I will come back in next month and will release
aufs4.2.

Sorry for your inconvenient and thank you for your patience
J. R. Okajima
```

**Comment by attilaolah** [comment]
@paralin, mind if I ask what is the reason aufs is merged in this fork in the first place?

I'm trying to rebase https://github.com/hardkernel/linux/tree/odroidc-3.10.y to a more recent tag, and most of the merge conflicts come from aufs support. In fact, the reason we're 8000+ commits ahead of upstream is the merge of the aufs.

Why can't we just drop aufs from this fork, and instead rebase to a more recent mainline that has aufs merged, and perhaps apply the remaining aufs patches if we want that to be up to date?

**Comment by umiddelb** [comment]
@attilaolah aufs support was merged (for C1 and XU3) because I wanted to run docker, which doesn't perform pretty well without it. The 3.18 kernel introduces overlayfs which is supported by docker as well.  

So if you manage to rebase odroidc to 3.14 we have the chance to merge an up-to-date aufs patchset (aufs development for 3.10 has been retired by the end of 2014). If you even move forward to 3.18 or later we can skip aufs support and switch to overlayfs.

**Comment by attilaolah** [comment]
> If you even move forward to 3.18 or later we can skip aufs support and switch to overlayfs.

That sounds like a better approach to me. (I've only used Docker with OverlayFS so far and it was a bliss.)

My personal goal would be to reach 3.19, [because of this](https://github.com/kuba-moo/mt7601u#building-and-using).

I'll let you know if I manage to `rebase -i` that.

**Comment by paralin** [comment]
I also am using docker with buildroot. I wouldn't mind overlayfs

**Pull request closed without merging**
