### PR TITLE
Add unique UUID to odroid-joypads

### PR DESCRIPTION
**Pull request by shantigilbert**
This adds unique UUIDs to the Odroid-joypads

Original patch by @valadaa48, modified for the Odroid-go super

### CODE REVIEW

**Comment by JeonghwaCho** [comment]
Hi @shantigilbert,
We will check this and reply soon.

**Comment by JeonghwaCho** [comment]
@shantigilbert,
I've discussed this topic with HK team.

To avoid collisions with user space virtual input drivers and allows mapping to be pushed to upstream projects,
it's needed that vendor ID should always be 0x484B.

Also to organize existing and future models, we would like to use the following values for product, revision and name.
[ vendor, product, revision, name ]
OGA : 0x484B, 0x1000, 0x0100, "GO-Advance Gamepad"
OGA-BE : 0x484B, 0x1000, 0x0101, "GO-Advance Gamepad (rev 1.1)"
OGS : 0x484B, 0x1100, 0x0100, "GO-Super Gamepad"
Next model : 0x484B, 0x1200, 0x0100, "GO-Next Gamepad"

So if you have no objection for this rule, some parts of your patch should be modified.

**Comment by shantigilbert** [comment]
> 
> 
> @shantigilbert,
> I've discussed this topic with HK team.
> 
> To avoid collisions with user space virtual input drivers and allows mapping to be pushed to upstream projects,
> it's needed that vendor ID should always be 0x484B.
> 
> Also to organize existing and future models, we would like to use the following values for product, revision and name.
> [ vendor, product, revision, name ]
> OGA : 0x484B, 0x1000, 0x0100, "GO-Advance Gamepad"
> OGA-BE : 0x484B, 0x1000, 0x0101, "GO-Advance Gamepad (rev 1.1)"
> OGS : 0x484B, 0x1100, 0x0100, "GO-Super Gamepad"
> Next model : 0x484B, 0x1200, 0x0100, "GO-Next Gamepad"
> 
> So if you have no objection for this rule, some parts of your patch should be modified.

That seems perfect for me, this will distinguish all the gamepads from each other and distros that use the same image can coexist with all the configurations.

Feel free to do the changes to my PR or let me know if you wish me to do them.

**Comment by JeonghwaCho** [comment]
@shantigilbert,
Thank you for your confirmation.
I will merge your PR and add another commit to adjust IDs as shared with you.

**Pull request merged**
