### PR TITLE
Odroidxu3-3.10.y: update to 3.10.92; AUFS fixes; driver updates

### PR DESCRIPTION
**Pull request by moonman**
-Kernel updated to 3.10.92
-AUFS fixed for 3.10.83+ kernels
-r8152 update to 2.05 from 2.04 (of course commit for setting custom mac is preserved)
-rtl8812 updated to v4.3.14_13455 with 8821 enabled for some dongles (D-Link DWA-171A1 as an example)
All commits tested on Odroid-XU4 without any regressions.

### CODE REVIEW

**Comment by Obihoernchen** [comment]
I can confirm this.
Builds and works fine :+1: 

I've added xfs support (I don't need AUFS but xfs):
`diff arch/arm/configs/odroidxu3_defconfig .config`

``` diff
3c3
< # Linux/arm 3.10.82 Kernel Configuration
---
> # Linux/arm 3.10.92 Kernel Configuration
128d127
< CONFIG_USER_NS=y
131,132d129
< CONFIG_UIDGID_CONVERTED=y
< CONFIG_UIDGID_STRICT_TYPE_CHECKS=y
3718c3715,3720
< # CONFIG_XFS_FS is not set
---
> CONFIG_XFS_FS=m
> CONFIG_XFS_QUOTA=y
> CONFIG_XFS_POSIX_ACL=y
> CONFIG_XFS_RT=y
> # CONFIG_XFS_WARN is not set
> # CONFIG_XFS_DEBUG is not set
3831a3834
> # CONFIG_AUFS_FS is not set
```

Works fine as well.

**Comment by moonman** [comment]
Any feedback on this from the hardkernel team? Anything I should change or it can't be merged for any reason?
@Obihoernchen thanks for feedback, but xfs is not really on topic. Open a new PR for xfs support.

**Comment by mdrjr** [comment]
Hello @moonman sorry for the delay... I've been quite busy :( I'll look onto this today. Just do some tests :)

**Comment by moonman** [comment]
Thanks @mdrjr. No worries. I just wasn't sure whether my PR was not good or it was the busy problem :) Cheers

**Comment by mdrjr** [comment]
@moonman Thank you so much for this PR. I really appreciate it. Specially the 8812au fix up.

**Pull request merged**
